### PR TITLE
[Feature] Return depth from RoboHiveEnv

### LINKED ISSUE #2051: [Feature Request] Return depth from RoboHiveEnv
## Motivation

Simulated environments are capable of rendering depth images which can be very useful in downstream training as they enable 3D understanding of the task being performed.  RoboHive environments, simulated with mujoco, can render and return depth images along with RGB. However, this functionality is currently not exposed in the torchrl wrapper `RoboHiveEnv`.

## Solution

A flag enabling depth images to  be returned from `RoboHiveEnv`. The solution has been implemented [here](https://github.com/sriramsk1999/rl/commit/f8bd510741963b305eadd72bbd6b6f6ac6df6a1a)

## Checklist

- [X] I have checked that there is no similar issue in the repo (**required**)

### PR DESCRIPTION
**Pull request by sriramsk1999**
## Description

This PR adds a flag to enable returning of depth images from `RoboHiveEnv`.

## Motivation and Context

Described in #2051 
`close #2051`

- [X] I have raised an issue to propose this change (required for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Remove all that do not apply:

- [X] New feature (non-breaking change which adds core functionality)
- [X] Documentation (update in the documentation)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [X] I have read the [CONTRIBUTION](https://github.com/pytorch/rl/blob/main/CONTRIBUTING.md) guide (**required**)
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

(I don't see any tests specific to `RoboHiveEnv` so I have not added any tests.)

### CODE REVIEW

**Review by vmoens — COMMENTED** [review]
Cool! Can you also add a test in test_libs.py?

**Comment by sriramsk1999** [comment]
While adding the test, I noticed that the current test code was actually broken. I've raised PR #2062 with the changes, but some tests are failing. Will rebase and add new tests after that is merged.

**Comment by vmoens** [comment]
robohive tests raise an error bc the key can't be found, do you want me to investigate @sriramsk1999 ?

**Comment by sriramsk1999** [comment]
I got probably the same error, only for the `rpFrankaRobotiqData` environment. 

```
AssertionError: The keys of the specs and data do not match:
    - List of keys present in real but not in fake: set(),
    - List of keys present in fake but not in real: {('next', 'depths'), 'depths'}.
```

I haven't gotten around to checking out the error in detail yet, please feel free to have a look :) Will update if I find a fix.

**Comment by sriramsk1999** [comment]
All RoboHive tests are now passing:

-  `rpFrankaRobotiqData-v0` is the only environment that has pre-registered visual_keys, so `from_pixels` is overridden to True even if the user sets it to False. I don't think this is expected behaviour, so I've removed this snippet in [this commit](https://github.com/pytorch/rl/pull/2058/commits/7d8c693850654931a168d9f92d246c972fb08332)
- I've added `from_depths` as well to the tests but there are now 2k tests just for RoboHive and it takes a while to complete (20 min on my PC)
- Unit tests were failing because the environment was already registered. So I've enabled overriding the already registered env [here](https://github.com/pytorch/rl/pull/2058/commits/9c394120a9cc07737fe02ff059d2ab1d7adf8f98#diff-ccbe2efde180bfb5fdb4bf24c919c7712ef48af50f1989bbaa3705e8c8b07074L240)

**Review by vmoens — APPROVED** [review]
LGTM

**Pull request merged**
