### PR TITLE
[Example] Distributed Replay Buffer Prototype Example Implementation

### PR DESCRIPTION
**Pull request by adityagoel4512**
## Description

Prototype example distributed replay buffer implementation using LazyMemmapStorage and TensorDictReplayBuffer, with nodes communicating using torch.rpc. The implementation allows for 1 Trainer Node, 1 Replay Buffer Node, and N >= 1 Data Collector Nodes.

## Motivation and Context

This investigative example illustrates some patterns with which we can implement distributed RL algorithms with replay buffers using the torch.rl framework. It also helps us understand the abstractions and ideas that may be missing from the framework or may need adapting to make writing distributed RL algorithms natural and performant.

- [ ] I have raised an issue to propose this change ([required](https://github.com/pytorch/rl/issues) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Remove all that do not apply:

- [ x] Example (update in the folder of examples)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [ x] I have read the [CONTRIBUTION](https://github.com/pytorch/rl/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by vmoens** [comment]
this is soooo cool
Would you have time to have a look at why when a memmap tensor is sent on one end the other worker receives a regular tensor? Do you think we can easily make the other process receive a memmap tensor instead?

For instance, [this](https://github.com/pytorch/rl/blob/6bd3b4745ea8758f1fd570a238010dc5bb1ce73d/test/test_shared.py#L78-L99) receives memmap tensors from one process and those tensors are actually of memmap type.

But `torch.distributed` does not serialize things as `multiprocess` I guess...

**Comment by vmoens** [comment]
Note for future contributions: it's best if you don't develop on your main branch but if you branch out on your forked repo :)

**Comment by adityagoel4512** [comment]
> Add heading textAdd bold text, <Cmd+b>Add italic text, <Cmd+i>
> Add a quote, <Cmd+Shift+.>Add code, <Cmd+e>Add a link, <Cmd+k>
> Add a bulleted list, <Cmd+Shift+8>Add a numbered list, <Cmd+Shift+7>Add a task list, <Cmd+Shift+l>
> Directly mention a user or team
> Reference an issue, pull request, or discussion
> Add saved reply

Sure thing - would you prefer I create a new branch for this PR as well?

> Note for future contributions: it's best if you don't develop on your main branch but if you branch out on your forked repo :)

**Review by vmoens — COMMENTED** [review]
Great work!
Should we comment the example, or write a separate markdown file in the example directory to explain what this is about?

Personally I'd be in favour of commenting the code using [this syntax](https://sphinx-gallery.github.io/stable/tutorials/plot_parse.html#sphx-glr-tutorials-plot-parse-py) which will allow us to port that to the doc later on.

Do you think we can test the distributed replay buffer in the CI? It would be nice to cover that there.

**Comment by adityagoel4512** [comment]
> Great work! Should we comment the example, or write a separate markdown file in the example directory to explain what this is about?
> 
> Personally I'd be in favour of commenting the code using [this syntax](https://sphinx-gallery.github.io/stable/tutorials/plot_parse.html#sphx-glr-tutorials-plot-parse-py) which will allow us to port that to the doc later on.
> 
> Do you think we can test the distributed replay buffer in the CI? It would be nice to cover that there.

Ah yes I'll add some comments in the example. I'll investigate how best to test the distributed buffer now.

**Review by vmoens — APPROVED** [review]
Wonderful! Thanks a million for this!

**Pull request merged**
