### PR TITLE
[BugFix] Fix strict-length for spanning trajectories

### PR DESCRIPTION
**Pull request by vmoens**
Solves #1969  as discussed in the issue

To test the feature:
```python

from torchrl.data import ReplayBuffer, SliceSampler, LazyTensorStorage
from tensordict import TensorDict
import torch


trajectory0 = torch.tensor([3, 3, 0, 1, 1, 1, 2, 2, 2, 3])
trajectory1 = torch.arange(10)
trajectory = torch.stack([trajectory0, trajectory1], -1)

td = TensorDict({"trajectory": trajectory, "steps": torch.arange(10).view(10, 1).expand(10, 2)}, [10, 2]).transpose(-2, -1).clone()
print(td)

rb = ReplayBuffer(
    sampler=SliceSampler(traj_key="trajectory", num_slices=2),
    storage=LazyTensorStorage(20, ndim=2),
    batch_size=6
)

rb.extend(td)

s = rb.sample()
print(s["steps"])
print(s["trajectory"])
```

Which can give
```
tensor([9, 0, 1, 6, 7, 8])
tensor([3, 3, 3, 2, 2, 2])
```

cc @nicklashansen @dasGringuen @aalmuzairee

### CODE REVIEW

**Comment by vmoens** [comment]
This is much more complex than I thought haha
I'm pretty sure I can get it to work efficiently but that will require some thinking! 
Thanks for your patience guys

**Comment by nicklashansen** [comment]
> This is much more complex than I thought haha I'm pretty sure I can get it to work efficiently but that will require some thinking! Thanks for your patience guys

@vmoens no worries, we really appreciate it! let us know if you need anything from us :-)

**Comment by vmoens** [comment]
That was fun! 
I think I got it right now.
There are various cases that I needed to handle (multiple dims, storage at capacity or not, raising errors if not valid traj can be found).

If you guys want to give it a look I'll leave this PR open for a little longer

**Comment by nicklashansen** [comment]
@vmoens sorry that it took a little while to get back to you, but this looks great! we'll run some tests on our end and see if it resolves the issue :-)

**Pull request merged**
