### PR TITLE
[BugFix] Batched environments with non empty batch size

### PR DESCRIPTION
**Pull request by matteobettini**
This PR fixes BUG #773

### CODE REVIEW

**Review by vmoens — APPROVED** [review]
LGTM thanks!

**Comment by vmoens** [comment]
@matteobettini can I ask you to add a simple test in test_envs.py to test non regression of this feature?

**Comment by matteobettini** [comment]
I have added the test.

The test tests only the batch size of the `ParallelEnv` compised of envs with batch sizes.

If you for example try to go forward and run a step, you will encounter a series of issues that stem from the fact that when `_BatchedEnv` was created, it was not taken into account that environments can have their own batch sizes. This is also the reason why no Brax environment works when wrapped in a BatchedEnv.

I will open an issue on this as serveral important modifications have to be made to allow a `ParallelEnv` of envs with their own batch sizes

**Comment by vmoens** [comment]
The lint is failing, let's fix this and merge!

**Comment by matteobettini** [comment]
Should be fixed

**Pull request merged**
