### PR TITLE
[BugFix] Fixed import for importlib

### PR DESCRIPTION
**Pull request by DanilBaibak**
## Description

There is an issue with import importlib. [This cause the warning](https://github.com/pytorch/rl/blob/main/torchrl/_extension.py#L24) "Failed to import torchrl C++ binaries"  #1888 

## Testing

Tested locally - see screenshots
Screenshot 2024-02-15 at 16 31 05
Screenshot 2024-02-15 at 16 30 59

- [ ] I have raised an issue to propose this change ([required](https://github.com/pytorch/rl/issues) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Remove all that do not apply:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)
- [ ] Example (update in the folder of examples)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://github.com/pytorch/rl/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by vmoens** [comment]
Looks ok but I'm not sure it fixes the issue
We should test this on an apple silicon node
```
$ pip3 install torch==2.2 torchrl==0.3.0 torchvision==0.17
$ python -c """import torchrl
torchrl.data.PrioritizedSampler(100, 1.0, 1.0)
"""
```
and check it works even if the warning is raised. 
I suspect the wheels are broken on some platforms, if they're not this fix will suppress the unwanted warning.
I'll try this tonight!

**Comment by vmoens** [comment]
Testing on linux, the code snippet above gives no warning by the way

**Comment by DanilBaibak** [comment]
Let's wait until the M1 build is ready and than I can test it locally.

**Review by vmoens — COMMENTED** [review]
What about adding a quick smoke test in the M1 binary built

```
import torchrl
torchrl.data.PrioritizedSampler(100, 1.0, 1.0)
```

If this runs the C++ binaries have been built properly (and if a warning is raised it should be ignored and fixed).

**Pull request merged**
