### PR TITLE
[BugFix] fix formatting for VideoRecorder docstring

### PR DESCRIPTION
**Pull request by sriramsk1999**
## Description

Fixes the formatting for the VideoRecorder docstring example, which is [currently broken](https://pytorch.org/rl/reference/generated/torchrl.record.VideoRecorder.html).

## Types of changes

- [X] Documentation (update in the documentation)

## Checklist

- [X] I have read the [CONTRIBUTION](https://github.com/pytorch/rl/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [X] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by sriramsk1999** [comment]
Also, `torchrl.envs.transforms.Composite` is mentioned in the example docstring but it looks like this transform doesn't exist anymore, shall I delete it?

Hope to make more meaningful contributions in the future! :)

**Review by vmoens — APPROVED** [review]
LGTM thanks!

**Comment by vmoens** [comment]
> Also, torchrl.envs.transforms.Composite is mentioned in the example docstring but it looks like this transform doesn't exist anymore, shall I delete it?

I think it will work without the `transforms`: `torchrl.envs.Composite`. Sphinx links are a bit restrictive, it's not sufficient for the python import to work, you also need to declare the path explicitly.

**Comment by sriramsk1999** [comment]
I'm not sure I understand, I don't see any function for `torchrl.envs.Composite`, the closest I can find anywhere in the codebase is `torchrl.data.CompositeSpec`, which looks unrelated.

Either way, I tried with `torchrl.envs.Composite` and sphinx still doesn't pick up any link

**Comment by vmoens** [comment]
Oh yeah lol it's Compose not Composite 😅

**Comment by sriramsk1999** [comment]
Haha that makes a lot more sense. Fixed, and verified!

**Pull request merged**
