### PR TITLE
[BugFix] RoundRobinWriter, possible duplicated code in the extend method

### PR DESCRIPTION
**Pull request by albertbou92**
## Description

In the class _RoundRobinWriter_, in the _extend_ method, seems like some of the conditions could be unnecessary. Maybe I am missing something, but if 

`cur_size = self._cursor
`

seems like the last two conditions are duplicated code. The code raises no error, but maybe the extra conditions can be removed.

## Types of changes

What types of changes does your code introduce? Remove all that do not apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)
- [ ] Example (update in the folder of examples)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [ ] I have read the [CONTRIBUTION](https://github.com/pytorch/rl/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by vmoens — COMMENTED** [review]
LGTM! The implementation was odd, I agree.
Could you add a test in `TestPrototypeBuffers` to check that the cursor moves to the right position in the following cases:

1. Fill the replay buffer with less data than the storage max size (N < M)
2. Fill the replay buffer with as much data as storage max size (N=M), and add some more data in a second time with less data (N<M) => the cursor should be at N
3. Fill the replay buffer directly with more data than the storage max size (N > M), the cursor should be at N-M

**Review by vmoens — APPROVED** [review]
LGTM! 
Thanks agains for spotting this and solving it!

**Comment by albertbou92** [comment]
I think the extend method int he ReplayBuffer from replay_buffers.py also can be simplified. I added the same changes I suggested for RoundRobinWriter and also added tests.

**Comment by vmoens** [comment]
> I think the extend method in the ReplayBuffer from replay_buffers.py also can be simplified. I added the same changes I suggested for RoundRobinWriter and also added tests.

Cool thanks for that too!
Let's wait for the tests to pass and we're good to go

**Pull request merged**
