### PR TITLE
Windows Unittests on GHA

### PR DESCRIPTION
**Pull request by osalpekar**
Testing out how windows unittests (currently on CircleCI) work on GHA/Nova pipelines.

### CODE REVIEW

**Comment by osalpekar** [comment]
Looks like the [Windows GHA job](https://github.com/pytorch/rl/actions/runs/4881369052/jobs/8710185749?pr=1086) and the [CircleCI job](https://circleci.com/gh/pytorch/rl/280422) fail with the same error. cc @vmoens to have a look

**Comment by vmoens** [comment]
I managed to fix it today. Are the tests still failing?

**Comment by osalpekar** [comment]
> I managed to fix it today. Are the tests still failing?

Ah. Let me rebase to rekick the tests

**Comment by osalpekar** [comment]
@vmoens Looks like the job passed: https://github.com/pytorch/rl/actions/runs/4897049212/jobs/8744618547?pr=1086!

**Review by vmoens — APPROVED** [review]
LGTM!

**Comment by vmoens** [comment]
Is the plan to keep only the cpu tests on win?

**Comment by osalpekar** [comment]
> Is the plan to keep only the cpu tests on win?

If Windows GPU isn't a commonly used combination we can drop that job. Otherwise we can migrate in a separate PR

**Pull request merged**
