### PR TITLE
[Feature] Added support for vector-based rewards from environments in MO-Gymnasium

### PR DESCRIPTION
**Pull request by dennismalmgren**
## Description

I made a small edit to the spec creation code for gym-like environments to support generating vector-based zero-rewards, which multi-objective environments in MO-Gymnasium uses.

## Motivation and Context

When interacting directly with gym code, the GymWrapper code supports vector-based rewards from environments in the MO-Gymnasium library. However, there is an imaginary reward generated by torchrl on environment resets, and this causes issues when doing rollouts for example, when everything gets stacked in one tensordict. This small fix allows rollout code to handle MO-Gymnasium environments by letting the imaginary reward conform to the shape that the environment uses (but not to any value limitations in MO-gym or regular gyms).

I'm not entirely sure how to classify the issue (bug/feature), it depends on whether MO-gym is considered out of scope for the gym wrapper or not. There are other interacting aspects, such as re-using 'categorical_action_encoding', but this is also done for observations and should probably be reviewed separatly.

- [ ] I have raised an issue to propose this change ([required](https://github.com/pytorch/rl/issues) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Remove all that do not apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)
- [ ] Example (update in the folder of examples)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://github.com/pytorch/rl/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by vmoens — COMMENTED** [review]
Thanks for this! I love the idea
Some gym envs do not have a reward_space so I added a check for that.
Is this something we could cover in our tests?

**Comment by dennismalmgren** [comment]
Thanks!
I could try to create some tests but I looked through the suite and couldn’t find any obvious existing place for it. If you have an idea I’ll go ahead.

**Comment by vmoens** [comment]
We can add mo-gymnasium as a dependency and include this env in the tests
We just need to have one instance of that created in `test_libs.py` and tested with `check_env_specs(env)`.
The ideal place to install this would be in the `script_gyms/batch_scripts` directory, under the latest version of gymnasium (ie we should install mo-gymnasium after we install the latest gymnasium [here](https://github.com/pytorch/rl/blob/e66db532a450476c7cbd8882bdf9971ae37d6e13/.circleci/unittest/linux_libs/scripts_gym/batch_scripts.sh#L119-L144)).
I can do that or you can give it a shot if you'd like.

**Comment by vmoens** [comment]
Some updates:
I'm trying to find my way out with mo-gymnasium.
Basically they re-provide all the specs from gym but under mo-gymnasium which breaks the instance checks we have. 
So I should try to do these instance checks with some context variable that conditions which lib we're talking about... 
The gym ecosystem is 👌

**Comment by vmoens** [comment]
@dennismalmgren We're still working on a better integration of gym for this, see #1023.
Once this is merged I'll edit this PR with a proper MO env wrapper :)

**Pull request merged**
